# Generated by Django 5.1.3 on 2024-11-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_data_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='detalhe',
            field=models.TextField(null=True),
        ),
    ]
